INSERT INTO projects (title, image, description, description2, place, space) VALUES
('Lincoln High School', 'img/first-project-file.jpg', 
 'In a joint venture with Pacificmark Construction, we recently completed this new six-story high school for Portland Public Schools. Built on the athletic fields of the current high school’s campus with students remaining in the existing building during construction, safety was the number one priority in the team’s construction efforts.',
 'This 292,000 SF high school is a six-story urban “high-rise” building, designed to accommodate a surge in student population in Portland Public Schools. The school was constructed on the athletic fields at one end of the school’s campus, which allowed students to occupy the current facility during construction; stringent safety protocols and intensive preconstruction planning protected students on the active campus. The new building includes specialized classrooms for 2D and 3D fine arts, adjacent flex spaces, STEM labs, and a maker space. The building has a variety of sustainability features and innovative wayfinding to help students and staff navigate the “high-rise” wing of the school. New athletic facilities include a 1,700-seat main gym, auxiliary gym, weight room, wrestling/dance room, and a new track and field. Primary features include a new commons and outdoor plaza at the main entrance; the team worked with Portland’s Regional Arts and Culture Council on a large mural that now fronts the building. Also included are a new 500-seat auditorium, black box theatre, dedicated band and choir classrooms and associated practice rooms, along with a career technical education space.',
 'Portland, OR', '44.5rem'),

('Wild Ginger Restaurant', 'img/second-project.jpg', 
 'The newest addition to the Wild Ginger family of restaurants, this location is in the booming South Lake Union neighborhood of Seattle. Located at 8th and Blanchard on the bottom floor of Clise Properties’ McKenzie Seattle, a new luxury apartment building built by Hoffman, the new spot has the same Wild Ginger feel Seattle knows and loves but on a smaller scale. Seating approximately 150 people and offering outdoor patio options, the space provides guests with an intimate dining experience. The high-end finishes had long lead times, leaving no room for error in the five months of construction.',
 '',
 'Seattle, WA', '41rem'),

('Public Works Facility', 'img/third-project.jpg', 
 'The new Public Works Facility will serve the community well into the future as the central hub for the construction, maintenance, and operation of Hillsboro’s transportation network, sanitary sewer systems, and stormwater systems. It includes a 25,000 SF operations facility, a 9,000 SF fleet maintenance shop, a 40,000 SF area containing material and vehicle storage, plus a vehicle wash facility. The project team completed the project in phases to minimize operation impacts during construction and to contend with active campus roads and wetlands mitigation. We collaborated closely with the owner and design team to develop and construct an on-budget project using BIM-driven MEP design coordination and constructability reviews. The project is built on a 16-acre site intended to eventually accommodate a multi-building public works campus. We helped the City to install infrastructure and systems that will grow with the phased campus development.',
 '',
 'Hillsboro, OR', '43.5rem'),

('Founders Hall', 'img/fourth-project.jpg', 
 'We led an integrated design-build team with the University of Washington and LMN Architects to expand the Foster School of Business with an 85,500 square foot building on the site of the existing MacKenzie Hall. The new building, Founders Hall, includes classrooms, program offices, research centers, career services offices, interaction spaces, event spaces, and amenity spaces to augment PACCAR and Dempsey Halls and support the School’s vision and goals.',
 '',
 'Seattle, WA', '51.3rem'),

('Reservoir Improvements', 'img/fifth-project.jpg', 
 'Our’s water specialists take on a challenging project: building a 15-million-gallon concrete storage reservoir, buried 100 feet deep. Designed to replace two again open-water reservoirs, the new reservoir will be put into service in 2020.',
 'EPA/Homeland Security requirements prompted this massive project for the Portland Water Bureau, which began in 2016. UrbanRise is replacing existing open-water Reservoirs 3 and 4 with a buried 15-million-gallon concrete storage reservoir that is 100 feet deep and 800 feet long. Due to the projected 18 inches of tank settlement, the reservoir will be put into service in 2020 but will settle for two years. The existing 150-year-old historic Dams 3 and 4 and the gate houses will also undergo a multi-million-dollar historic restoration. The new tank will be covered with interactive public parks and eight-foot high, 1000-foot-long cascading waterfalls. All the work is being done at the bottom of an ancient moving slide being monitored with 300 prisms beaming up to satellites to track real-time movement of the hillside.',
 'Portland, OR', '39.4rem'),

('Fab D1X Mod 2', 'img/sixth-project.jpg', 
 'D1X Mod 2 was established as a technology development hub for both new technology generations as well as a manufacturing equipment set capable of a new wafer size. To enable the client’s next-generation process technologies, our team took a flexible approach to construction, staying poised to adapt to their next big breakthrough while strictly adhering to the client’s stringent non-disruption protocols and expectations.',
 'This facility was a ‘copy exact’ of D1X Mod 1, including 1,300,000 GSF, 240,000 SF of cleanroom space (562,000 SF gross that includes ancillary clean non-production spaces), a process utility building (PUB), a boiler-chiller plant (BCP), and a fab support building (FSB) with labs and other facilities. During our 25 years of building facilities for the world’s leading manufacturer of microchips, we have evolved our construction services to support the requirements of next-generation process technologies. We built high-tech research and development centers where our client could pursue cutting-edge ideas, then returned to build manufacturing facilities around the R&D sites so they could bring those ideas to life on a large scale.',
 'Hillsboro, OR', '49.5rem');